require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe JoinPointCategoriesController do

  # This should return the minimal set of attributes required to create a valid
  # JoinPointCategory. As you add validations to JoinPointCategory, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # JoinPointCategoriesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all join_point_categories as @join_point_categories" do
      join_tochka_tcategory = JoinPointCategory.create! valid_attributes
      get :index, {}, valid_session
      assigns(:join_point_categories).should eq([join_tochka_tcategory])
    end
  end

  describe "GET show" do
    it "assigns the requested join_tochka_tcategory as @join_tochka_tcategory" do
      join_tochka_tcategory = JoinPointCategory.create! valid_attributes
      get :show, {:id => join_tochka_tcategory.to_param}, valid_session
      assigns(:join_point_category).should eq(join_tochka_tcategory)
    end
  end

  describe "GET new" do
    it "assigns a new join_tochka_tcategory as @join_tochka_tcategory" do
      get :new, {}, valid_session
      assigns(:join_point_category).should be_a_new(JoinPointCategory)
    end
  end

  describe "GET edit" do
    it "assigns the requested join_tochka_tcategory as @join_tochka_tcategory" do
      join_tochka_tcategory = JoinPointCategory.create! valid_attributes
      get :edit, {:id => join_tochka_tcategory.to_param}, valid_session
      assigns(:join_point_category).should eq(join_tochka_tcategory)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new JoinPointCategory" do
        expect {
          post :create, {:join_point_category => valid_attributes}, valid_session
        }.to change(JoinPointCategory, :count).by(1)
      end

      it "assigns a newly created join_tochka_tcategory as @join_tochka_tcategory" do
        post :create, {:join_point_category => valid_attributes}, valid_session
        assigns(:join_point_category).should be_a(JoinPointCategory)
        assigns(:join_point_category).should be_persisted
      end

      it "redirects to the created join_tochka_tcategory" do
        post :create, {:join_point_category => valid_attributes}, valid_session
        response.should redirect_to(JoinPointCategory.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved join_tochka_tcategory as @join_tochka_tcategory" do
        # Trigger the behavior that occurs when invalid params are submitted
        JoinPointCategory.any_instance.stub(:save).and_return(false)
        post :create, {:join_point_category => {}}, valid_session
        assigns(:join_point_category).should be_a_new(JoinPointCategory)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        JoinPointCategory.any_instance.stub(:save).and_return(false)
        post :create, {:join_point_category => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested join_tochka_tcategory" do
        join_tochka_tcategory = JoinPointCategory.create! valid_attributes
        # Assuming there are no other join_point_categories in the database, this
        # specifies that the JoinPointCategory created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        JoinPointCategory.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => join_tochka_tcategory.to_param, :join_point_category => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested join_tochka_tcategory as @join_tochka_tcategory" do
        join_tochka_tcategory = JoinPointCategory.create! valid_attributes
        put :update, {:id => join_tochka_tcategory.to_param, :join_point_category => valid_attributes}, valid_session
        assigns(:join_point_category).should eq(join_tochka_tcategory)
      end

      it "redirects to the join_tochka_tcategory" do
        join_tochka_tcategory = JoinPointCategory.create! valid_attributes
        put :update, {:id => join_tochka_tcategory.to_param, :join_point_category => valid_attributes}, valid_session
        response.should redirect_to(join_tochka_tcategory)
      end
    end

    describe "with invalid params" do
      it "assigns the join_tochka_tcategory as @join_tochka_tcategory" do
        join_tochka_tcategory = JoinPointCategory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        JoinPointCategory.any_instance.stub(:save).and_return(false)
        put :update, {:id => join_tochka_tcategory.to_param, :join_point_category => {}}, valid_session
        assigns(:join_point_category).should eq(join_tochka_tcategory)
      end

      it "re-renders the 'edit' template" do
        join_tochka_tcategory = JoinPointCategory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        JoinPointCategory.any_instance.stub(:save).and_return(false)
        put :update, {:id => join_tochka_tcategory.to_param, :join_point_category => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested join_tochka_tcategory" do
      join_tochka_tcategory = JoinPointCategory.create! valid_attributes
      expect {
        delete :destroy, {:id => join_tochka_tcategory.to_param}, valid_session
      }.to change(JoinPointCategory, :count).by(-1)
    end

    it "redirects to the join_point_categories list" do
      join_tochka_tcategory = JoinPointCategory.create! valid_attributes
      delete :destroy, {:id => join_tochka_tcategory.to_param}, valid_session
      response.should redirect_to(join_tochka_tcategories_url)
    end
  end

end
