require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TochkasController do

  # This should return the minimal set of attributes required to create a valid
  # Tochka. As you add validations to Tochka, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TochkasController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all tochkas as @tochkas" do
      tochka = Tochka.create! valid_attributes
      get :index, {}, valid_session
      assigns(:tochkas).should eq([tochka])
    end
  end

  describe "GET show" do
    it "assigns the requested tochka as @tochka" do
      tochka = Tochka.create! valid_attributes
      get :show, {:id => tochka.to_param}, valid_session
      assigns(:tochka).should eq(tochka)
    end
  end

  describe "GET new" do
    it "assigns a new tochka as @tochka" do
      get :new, {}, valid_session
      assigns(:tochka).should be_a_new(Tochka)
    end
  end

  describe "GET edit" do
    it "assigns the requested tochka as @tochka" do
      tochka = Tochka.create! valid_attributes
      get :edit, {:id => tochka.to_param}, valid_session
      assigns(:tochka).should eq(tochka)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Tochka" do
        expect {
          post :create, {:tochka => valid_attributes}, valid_session
        }.to change(Tochka, :count).by(1)
      end

      it "assigns a newly created tochka as @tochka" do
        post :create, {:tochka => valid_attributes}, valid_session
        assigns(:tochka).should be_a(Tochka)
        assigns(:tochka).should be_persisted
      end

      it "redirects to the created tochka" do
        post :create, {:tochka => valid_attributes}, valid_session
        response.should redirect_to(Tochka.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved tochka as @tochka" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tochka.any_instance.stub(:save).and_return(false)
        post :create, {:tochka => {}}, valid_session
        assigns(:tochka).should be_a_new(Tochka)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tochka.any_instance.stub(:save).and_return(false)
        post :create, {:tochka => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested tochka" do
        tochka = Tochka.create! valid_attributes
        # Assuming there are no other tochkas in the database, this
        # specifies that the Tochka created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Tochka.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => tochka.to_param, :tochka => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested tochka as @tochka" do
        tochka = Tochka.create! valid_attributes
        put :update, {:id => tochka.to_param, :tochka => valid_attributes}, valid_session
        assigns(:tochka).should eq(tochka)
      end

      it "redirects to the tochka" do
        tochka = Tochka.create! valid_attributes
        put :update, {:id => tochka.to_param, :tochka => valid_attributes}, valid_session
        response.should redirect_to(tochka)
      end
    end

    describe "with invalid params" do
      it "assigns the tochka as @tochka" do
        tochka = Tochka.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tochka.any_instance.stub(:save).and_return(false)
        put :update, {:id => tochka.to_param, :tochka => {}}, valid_session
        assigns(:tochka).should eq(tochka)
      end

      it "re-renders the 'edit' template" do
        tochka = Tochka.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tochka.any_instance.stub(:save).and_return(false)
        put :update, {:id => tochka.to_param, :tochka => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested tochka" do
      tochka = Tochka.create! valid_attributes
      expect {
        delete :destroy, {:id => tochka.to_param}, valid_session
      }.to change(Tochka, :count).by(-1)
    end

    it "redirects to the tochkas list" do
      tochka = Tochka.create! valid_attributes
      delete :destroy, {:id => tochka.to_param}, valid_session
      response.should redirect_to(tochkas_url)
    end
  end

end
